# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/dine-opplysninger
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50

port: 8080

healthcheck:
  liveness:
    path: /arbeid/dineopplysninger/internal/isAlive
    initialDelay: 60
  readiness:
    path: /arbeid/dineopplysninger/internal/isReady
    initialDelay: 60

team: bos

alertProfiles:
  - common-java-modules

prometheus:
  enabled: true
  path: /arbeid/dineopplysninger/internal/metrics

resources:
  limits:
    cpu: 3
    memory: 768Mi
  requests:
    memory: 512Mi

fasitResources:
  used:
    - alias: loadbalancer:dine-opplysninger
      resourceType: loadbalancerconfig
    - alias: appres.cms
      resourceType: baseUrl
    - alias: appdynamics
      resourceType: applicationproperties

    # oidc med AzureAD B2C
    - alias: loginservice
      resourceType: restservice
    - alias: aad_b2c_clientid
      resourceType: credential
    - alias: aad_b2c_discovery
      resourceType: baseurl

    # lenker
    - alias: sykefravaer
      resourceType: baseUrl
    - alias: aktivitetsplan
      resourceType: baseUrl
    - alias: dittnav.link
      resourceType: baseUrl
    - alias: veientilarbeid
      resourceType: baseurl
    - alias: arbeidssokerregistrering
      resourceType: baseurl

webproxy: true
