apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dine-opplysninger
  namespace: {{namespace}}
  cluster:
    - dev-sbs
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/dine-opplysninger/dine-opplysninger:{{version}}
  port: 8080
  liveness:
    path: /arbeid/dineopplysninger/internal/isAlive
    initialDelay: 15
  readiness:
    path: /arbeid/dineopplysninger/internal/isReady
    initialDelay: 15
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi
  prometheus:
    enabled: true
    path: /arbeid/dineopplysninger/internal/metrics
  webproxy: true
  ingresses:
    - www-{{namespace}}.nav.no/arbeid/dineopplysninger
  env:
    - LOGINSERVICE_URL
    - APPRES_CMS_URL
    - UNLEASH_API_URL
    - SYKEFRAVAER_URL
    - AKTIVITETSPLAN_URL
    - VEIENTILARBEID_URL
    - ARBEIDSSOKERREGISTRERING_URL
    - DITTNAV_URL
