apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dine-opplysninger
  namespace: default
  cluster:
    - prod-sbs
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/dine-opplysninger/dine-opplysninger:{{version}}
  port: 8080
  liveness:
    path: /arbeid/dineopplysninger/internal/isAlive
    initialDelay: 10
  readiness:
    path: /arbeid/dineopplysninger/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 80
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi
prometheus:
  enabled: true
  path: /arbeid/dineopplysninger/internal/metrics
ingresses:
  - www.nav.no/arbeid/dineopplysninger